name: conversational_english
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  power_state: ^1.0.0
  dio: ^5.7.0
  intl: ^0.20.1
  flutter_svg: ^2.0.10+1 
  # firebase_core: ^3.6.0
  # google_sign_in: ^6.2.1
  # firebase_auth: ^5.3.1
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  collection: ^1.19.1
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0
flutter:

  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/drawer/
  fonts:
    - family: Salsa-Regular
      fonts:
        - asset: assets/fonts/Salsa-Regular.ttf    
